include $(GPSEE_SRC_DIR)/system_detect.mk
APR_PROJECT 	= TRUE

SURELYNX_PREFIX_DIR	?= /var/surelynx
SURELYNX_PLATFORM 	?= $(UNAME_SYSTEM)-$(UNAME_RELEASE)-$(UNAME_MACHINE)-$(UNAME_CPU)
SURELYNX_PLATFORM_DIR	?= $(SURELYNX_PREFIX_DIR)/platform/$(SURELYNX_PLATFORM)

DEFAULT_GPSEE_PREFIX_DIR = $(SURELYNX_PREFIX_DIR)/gpsee
GPSEE_PREFIX_DIR	 = $(SURELYNX_PREFIX_DIR)/gpsee
GSR_SHEBANG_LINK	 = /var/surelynx/bin/gsr

GPSEE_C_DEFINES	+= NO_GPSEE_FLOCK HAVE_ICONV HAVE_APR

LDFLAGS	 	  += -L$(SURELYNX_PLATFORM_DIR)/lib/apr_surelynx -L$(SURELYNX_PLATFORM_DIR)/lib -L$(SURELYNX_PREFIX_DIR)/apr/lib \
		     -R$(SURELYNX_PLATFORM_DIR)/lib/apr_surelynx -R$(SURELYNX_PLATFORM_DIR)/lib -R$(SURELYNX_PREFIX_DIR)/apr/lib
LDLIBS		  := -lapr_surelynx -lapr-1 $(LDLIBS)
CPPFLAGS 	  := -D__SURELYNX__ -I$(SURELYNX_PREFIX_DIR)/include/apr -I/var/surelynx/include/apr_surelynx -I/var/surelynx/include $(CPPFLAGS)

NO_VERSION_O_RULES = True
include $(GPSEE_SRC_DIR)/unix_stream.mk

