static JSConstDoubleSpec easycurl_options[] = {
{10001, "CURLOPT_FILE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10002, "CURLOPT_URL", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{3, "CURLOPT_PORT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10004, "CURLOPT_PROXY", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10005, "CURLOPT_USERPWD", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10006, "CURLOPT_PROXYUSERPWD", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10007, "CURLOPT_RANGE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10009, "CURLOPT_INFILE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10010, "CURLOPT_ERRORBUFFER", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20011, "CURLOPT_WRITEFUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20012, "CURLOPT_READFUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{13, "CURLOPT_TIMEOUT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{14, "CURLOPT_INFILESIZE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10015, "CURLOPT_POSTFIELDS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10016, "CURLOPT_REFERER", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10017, "CURLOPT_FTPPORT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10018, "CURLOPT_USERAGENT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{19, "CURLOPT_LOW_SPEED_LIMIT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20, "CURLOPT_LOW_SPEED_TIME", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{21, "CURLOPT_RESUME_FROM", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10022, "CURLOPT_COOKIE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10023, "CURLOPT_HTTPHEADER", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10024, "CURLOPT_HTTPPOST", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10025, "CURLOPT_SSLCERT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10026, "CURLOPT_KEYPASSWD", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{27, "CURLOPT_CRLF", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10028, "CURLOPT_QUOTE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10029, "CURLOPT_WRITEHEADER", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10031, "CURLOPT_COOKIEFILE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{32, "CURLOPT_SSLVERSION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{33, "CURLOPT_TIMECONDITION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{34, "CURLOPT_TIMEVALUE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10036, "CURLOPT_CUSTOMREQUEST", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10037, "CURLOPT_STDERR", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10039, "CURLOPT_POSTQUOTE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10040, "CURLOPT_WRITEINFO", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{41, "CURLOPT_VERBOSE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{42, "CURLOPT_HEADER", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{43, "CURLOPT_NOPROGRESS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{44, "CURLOPT_NOBODY", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{45, "CURLOPT_FAILONERROR", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{46, "CURLOPT_UPLOAD", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{47, "CURLOPT_POST", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{48, "CURLOPT_DIRLISTONLY", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{50, "CURLOPT_APPEND", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{51, "CURLOPT_NETRC", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{52, "CURLOPT_FOLLOWLOCATION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{53, "CURLOPT_TRANSFERTEXT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{54, "CURLOPT_PUT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20056, "CURLOPT_PROGRESSFUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10057, "CURLOPT_PROGRESSDATA", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{58, "CURLOPT_AUTOREFERER", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{59, "CURLOPT_PROXYPORT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{60, "CURLOPT_POSTFIELDSIZE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{61, "CURLOPT_HTTPPROXYTUNNEL", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10062, "CURLOPT_INTERFACE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10063, "CURLOPT_KRBLEVEL", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{64, "CURLOPT_SSL_VERIFYPEER", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10065, "CURLOPT_CAINFO", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{68, "CURLOPT_MAXREDIRS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{69, "CURLOPT_FILETIME", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10070, "CURLOPT_TELNETOPTIONS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{71, "CURLOPT_MAXCONNECTS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{72, "CURLOPT_CLOSEPOLICY", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{74, "CURLOPT_FRESH_CONNECT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{75, "CURLOPT_FORBID_REUSE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10076, "CURLOPT_RANDOM_FILE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10077, "CURLOPT_EGDSOCKET", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{78, "CURLOPT_CONNECTTIMEOUT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20079, "CURLOPT_HEADERFUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{80, "CURLOPT_HTTPGET", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{81, "CURLOPT_SSL_VERIFYHOST", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10082, "CURLOPT_COOKIEJAR", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10083, "CURLOPT_SSL_CIPHER_LIST", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{84, "CURLOPT_HTTP_VERSION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{85, "CURLOPT_FTP_USE_EPSV", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10086, "CURLOPT_SSLCERTTYPE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10087, "CURLOPT_SSLKEY", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10088, "CURLOPT_SSLKEYTYPE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10089, "CURLOPT_SSLENGINE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{90, "CURLOPT_SSLENGINE_DEFAULT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{91, "CURLOPT_DNS_USE_GLOBAL_CACHE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{92, "CURLOPT_DNS_CACHE_TIMEOUT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10093, "CURLOPT_PREQUOTE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20094, "CURLOPT_DEBUGFUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10095, "CURLOPT_DEBUGDATA", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{96, "CURLOPT_COOKIESESSION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10097, "CURLOPT_CAPATH", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{98, "CURLOPT_BUFFERSIZE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{99, "CURLOPT_NOSIGNAL", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10100, "CURLOPT_SHARE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{101, "CURLOPT_PROXYTYPE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10102, "CURLOPT_ENCODING", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10103, "CURLOPT_PRIVATE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{105, "CURLOPT_UNRESTRICTED_AUTH", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{106, "CURLOPT_FTP_USE_EPRT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{107, "CURLOPT_HTTPAUTH", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20108, "CURLOPT_SSL_CTX_FUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10109, "CURLOPT_SSL_CTX_DATA", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{110, "CURLOPT_FTP_CREATE_MISSING_DIRS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{111, "CURLOPT_PROXYAUTH", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{112, "CURLOPT_FTP_RESPONSE_TIMEOUT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{113, "CURLOPT_IPRESOLVE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{114, "CURLOPT_MAXFILESIZE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10118, "CURLOPT_NETRC_FILE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{119, "CURLOPT_USE_SSL", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{121, "CURLOPT_TCP_NODELAY", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{129, "CURLOPT_FTPSSLAUTH", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20130, "CURLOPT_IOCTLFUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10131, "CURLOPT_IOCTLDATA", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10134, "CURLOPT_FTP_ACCOUNT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10135, "CURLOPT_COOKIELIST", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{136, "CURLOPT_IGNORE_CONTENT_LENGTH", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{137, "CURLOPT_FTP_SKIP_PASV_IP", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{138, "CURLOPT_FTP_FILEMETHOD", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{139, "CURLOPT_LOCALPORT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{140, "CURLOPT_LOCALPORTRANGE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{141, "CURLOPT_CONNECT_ONLY", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20142, "CURLOPT_CONV_FROM_NETWORK_FUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20143, "CURLOPT_CONV_TO_NETWORK_FUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10147, "CURLOPT_FTP_ALTERNATIVE_TO_USER", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20148, "CURLOPT_SOCKOPTFUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10149, "CURLOPT_SOCKOPTDATA", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{150, "CURLOPT_SSL_SESSIONID_CACHE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{151, "CURLOPT_SSH_AUTH_TYPES", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10152, "CURLOPT_SSH_PUBLIC_KEYFILE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10153, "CURLOPT_SSH_PRIVATE_KEYFILE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{154, "CURLOPT_FTP_SSL_CCC", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{155, "CURLOPT_TIMEOUT_MS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{156, "CURLOPT_CONNECTTIMEOUT_MS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{157, "CURLOPT_HTTP_TRANSFER_DECODING", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{158, "CURLOPT_HTTP_CONTENT_DECODING", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{159, "CURLOPT_NEW_FILE_PERMS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{160, "CURLOPT_NEW_DIRECTORY_PERMS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{161, "CURLOPT_POSTREDIR", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20163, "CURLOPT_OPENSOCKETFUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10164, "CURLOPT_OPENSOCKETDATA", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10165, "CURLOPT_COPYPOSTFIELDS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{166, "CURLOPT_PROXY_TRANSFER_MODE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20167, "CURLOPT_SEEKFUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10168, "CURLOPT_SEEKDATA", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10169, "CURLOPT_CRLFILE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10170, "CURLOPT_ISSUERCERT", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{171, "CURLOPT_ADDRESS_SCOPE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{172, "CURLOPT_CERTINFO", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10173, "CURLOPT_USERNAME", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10174, "CURLOPT_PASSWORD", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10175, "CURLOPT_PROXYUSERNAME", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10176, "CURLOPT_PROXYPASSWORD", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10177, "CURLOPT_NOPROXY", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{178, "CURLOPT_TFTP_BLKSIZE", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{181, "CURLOPT_PROTOCOLS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{182, "CURLOPT_REDIR_PROTOCOLS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10183, "CURLOPT_SSH_KNOWNHOSTS", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{20184, "CURLOPT_SSH_KEYFUNCTION", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{10185, "CURLOPT_SSH_KEYDATA", JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}},
{0,0,0,{0,0,0}}
};
int option_expected_type(int opt) {
switch (opt) {
case CURLOPT_PORT: 
case CURLOPT_TIMEOUT: 
case CURLOPT_INFILESIZE: 
case CURLOPT_LOW_SPEED_LIMIT: 
case CURLOPT_LOW_SPEED_TIME: 
case CURLOPT_RESUME_FROM: 
case CURLOPT_CRLF: 
case CURLOPT_SSLVERSION: 
case CURLOPT_TIMECONDITION: 
case CURLOPT_TIMEVALUE: 
case CURLOPT_VERBOSE: 
case CURLOPT_HEADER: 
case CURLOPT_NOPROGRESS: 
case CURLOPT_NOBODY: 
case CURLOPT_FAILONERROR: 
case CURLOPT_UPLOAD: 
case CURLOPT_POST: 
case CURLOPT_DIRLISTONLY: 
case CURLOPT_APPEND: 
case CURLOPT_NETRC: 
case CURLOPT_FOLLOWLOCATION: 
case CURLOPT_TRANSFERTEXT: 
case CURLOPT_PUT: 
case CURLOPT_AUTOREFERER: 
case CURLOPT_PROXYPORT: 
case CURLOPT_POSTFIELDSIZE: 
case CURLOPT_HTTPPROXYTUNNEL: 
case CURLOPT_SSL_VERIFYPEER: 
case CURLOPT_MAXREDIRS: 
case CURLOPT_FILETIME: 
case CURLOPT_MAXCONNECTS: 
case CURLOPT_CLOSEPOLICY: 
case CURLOPT_FRESH_CONNECT: 
case CURLOPT_FORBID_REUSE: 
case CURLOPT_CONNECTTIMEOUT: 
case CURLOPT_HTTPGET: 
case CURLOPT_SSL_VERIFYHOST: 
case CURLOPT_HTTP_VERSION: 
case CURLOPT_FTP_USE_EPSV: 
case CURLOPT_SSLENGINE_DEFAULT: 
case CURLOPT_DNS_USE_GLOBAL_CACHE: 
case CURLOPT_DNS_CACHE_TIMEOUT: 
case CURLOPT_COOKIESESSION: 
case CURLOPT_BUFFERSIZE: 
case CURLOPT_NOSIGNAL: 
case CURLOPT_PROXYTYPE: 
case CURLOPT_UNRESTRICTED_AUTH: 
case CURLOPT_FTP_USE_EPRT: 
case CURLOPT_HTTPAUTH: 
case CURLOPT_FTP_CREATE_MISSING_DIRS: 
case CURLOPT_PROXYAUTH: 
case CURLOPT_FTP_RESPONSE_TIMEOUT: 
case CURLOPT_IPRESOLVE: 
case CURLOPT_MAXFILESIZE: 
case CURLOPT_USE_SSL: 
case CURLOPT_TCP_NODELAY: 
case CURLOPT_FTPSSLAUTH: 
case CURLOPT_IGNORE_CONTENT_LENGTH: 
case CURLOPT_FTP_SKIP_PASV_IP: 
case CURLOPT_FTP_FILEMETHOD: 
case CURLOPT_LOCALPORT: 
case CURLOPT_LOCALPORTRANGE: 
case CURLOPT_CONNECT_ONLY: 
case CURLOPT_SSL_SESSIONID_CACHE: 
case CURLOPT_SSH_AUTH_TYPES: 
case CURLOPT_FTP_SSL_CCC: 
case CURLOPT_TIMEOUT_MS: 
case CURLOPT_CONNECTTIMEOUT_MS: 
case CURLOPT_HTTP_TRANSFER_DECODING: 
case CURLOPT_HTTP_CONTENT_DECODING: 
case CURLOPT_NEW_FILE_PERMS: 
case CURLOPT_NEW_DIRECTORY_PERMS: 
case CURLOPT_POSTREDIR: 
case CURLOPT_PROXY_TRANSFER_MODE: 
case CURLOPT_ADDRESS_SCOPE: 
case CURLOPT_CERTINFO: 
case CURLOPT_TFTP_BLKSIZE: 
case CURLOPT_PROTOCOLS: 
case CURLOPT_REDIR_PROTOCOLS: 
return 0;
case CURLOPT_FILE: 
case CURLOPT_URL: 
case CURLOPT_PROXY: 
case CURLOPT_USERPWD: 
case CURLOPT_PROXYUSERPWD: 
case CURLOPT_RANGE: 
case CURLOPT_INFILE: 
case CURLOPT_ERRORBUFFER: 
case CURLOPT_POSTFIELDS: 
case CURLOPT_REFERER: 
case CURLOPT_FTPPORT: 
case CURLOPT_USERAGENT: 
case CURLOPT_COOKIE: 
case CURLOPT_HTTPHEADER: 
case CURLOPT_HTTPPOST: 
case CURLOPT_SSLCERT: 
case CURLOPT_KEYPASSWD: 
case CURLOPT_QUOTE: 
case CURLOPT_WRITEHEADER: 
case CURLOPT_COOKIEFILE: 
case CURLOPT_CUSTOMREQUEST: 
case CURLOPT_STDERR: 
case CURLOPT_POSTQUOTE: 
case CURLOPT_WRITEINFO: 
case CURLOPT_PROGRESSDATA: 
case CURLOPT_INTERFACE: 
case CURLOPT_KRBLEVEL: 
case CURLOPT_CAINFO: 
case CURLOPT_TELNETOPTIONS: 
case CURLOPT_RANDOM_FILE: 
case CURLOPT_EGDSOCKET: 
case CURLOPT_COOKIEJAR: 
case CURLOPT_SSL_CIPHER_LIST: 
case CURLOPT_SSLCERTTYPE: 
case CURLOPT_SSLKEY: 
case CURLOPT_SSLKEYTYPE: 
case CURLOPT_SSLENGINE: 
case CURLOPT_PREQUOTE: 
case CURLOPT_DEBUGDATA: 
case CURLOPT_CAPATH: 
case CURLOPT_SHARE: 
case CURLOPT_ENCODING: 
case CURLOPT_PRIVATE: 
case CURLOPT_SSL_CTX_DATA: 
case CURLOPT_NETRC_FILE: 
case CURLOPT_IOCTLDATA: 
case CURLOPT_FTP_ACCOUNT: 
case CURLOPT_COOKIELIST: 
case CURLOPT_FTP_ALTERNATIVE_TO_USER: 
case CURLOPT_SOCKOPTDATA: 
case CURLOPT_SSH_PUBLIC_KEYFILE: 
case CURLOPT_SSH_PRIVATE_KEYFILE: 
case CURLOPT_OPENSOCKETDATA: 
case CURLOPT_COPYPOSTFIELDS: 
case CURLOPT_SEEKDATA: 
case CURLOPT_CRLFILE: 
case CURLOPT_ISSUERCERT: 
case CURLOPT_USERNAME: 
case CURLOPT_PASSWORD: 
case CURLOPT_PROXYUSERNAME: 
case CURLOPT_PROXYPASSWORD: 
case CURLOPT_NOPROXY: 
case CURLOPT_SSH_KNOWNHOSTS: 
case CURLOPT_SSH_KEYDATA: 
return 1;
case CURLOPT_WRITEFUNCTION: 
case CURLOPT_READFUNCTION: 
case CURLOPT_PROGRESSFUNCTION: 
case CURLOPT_HEADERFUNCTION: 
case CURLOPT_DEBUGFUNCTION: 
case CURLOPT_SSL_CTX_FUNCTION: 
case CURLOPT_IOCTLFUNCTION: 
case CURLOPT_CONV_FROM_NETWORK_FUNCTION: 
case CURLOPT_CONV_TO_NETWORK_FUNCTION: 
case CURLOPT_SOCKOPTFUNCTION: 
case CURLOPT_OPENSOCKETFUNCTION: 
case CURLOPT_SEEKFUNCTION: 
case CURLOPT_SSH_KEYFUNCTION: 
return 2;
default: return -1;
}
}
