

#define EASYSPEC(XX) {XX, #XX, JSPROP_READONLY | JSPROP_PERMANENT | JSPROP_ENUMERATE, {0,0,0}}

static JSConstDoubleSpec easycurl_info[] = {
  EASYSPEC(CURLINFO_EFFECTIVE_URL),
  EASYSPEC(CURLINFO_RESPONSE_CODE),
  EASYSPEC(CURLINFO_TOTAL_TIME),
  EASYSPEC(CURLINFO_NAMELOOKUP_TIME),
  EASYSPEC(CURLINFO_CONNECT_TIME),
  EASYSPEC(CURLINFO_PRETRANSFER_TIME),
  EASYSPEC(CURLINFO_SIZE_UPLOAD),
  EASYSPEC(CURLINFO_SIZE_DOWNLOAD),
  EASYSPEC(CURLINFO_SPEED_DOWNLOAD),
  EASYSPEC(CURLINFO_SPEED_UPLOAD),
  EASYSPEC(CURLINFO_HEADER_SIZE),
  EASYSPEC(CURLINFO_REQUEST_SIZE),
  EASYSPEC(CURLINFO_SSL_VERIFYRESULT),
  EASYSPEC(CURLINFO_FILETIME),
  EASYSPEC(CURLINFO_CONTENT_LENGTH_DOWNLOAD),
  EASYSPEC(CURLINFO_CONTENT_LENGTH_UPLOAD),
  EASYSPEC(CURLINFO_STARTTRANSFER_TIME),
  EASYSPEC(CURLINFO_CONTENT_TYPE),
  EASYSPEC(CURLINFO_REDIRECT_TIME),
  EASYSPEC(CURLINFO_REDIRECT_COUNT),
  EASYSPEC(CURLINFO_PRIVATE),
  EASYSPEC(CURLINFO_HTTP_CONNECTCODE),
  EASYSPEC(CURLINFO_HTTPAUTH_AVAIL),
  EASYSPEC(CURLINFO_PROXYAUTH_AVAIL),
  EASYSPEC(CURLINFO_OS_ERRNO),
  EASYSPEC(CURLINFO_NUM_CONNECTS),
  EASYSPEC(CURLINFO_COOKIELIST),
  EASYSPEC(CURLINFO_LASTSOCKET),
  EASYSPEC(CURLINFO_FTP_ENTRY_PATH),
#ifdef CURLINFO_REDIRECT_URL
  EASYSPEC(CURLINFO_REDIRECT_URL),
#endif
  {0,0,0,{0,0,0}}
};

